### PR TITLE
Fix typo and grammar

### PR DESCRIPTION
**Pull request by HelderMagalhaes**

### CODE REVIEW

**Comment by bodewig** [comment]
thank you. Please remove the hunk that just changes whitespace at the top of TarArchiveEntry

**Comment by HelderMagalhaes** [comment]
> Please remove the hunk that just changes whitespace at the top of TarArchiveEntry

The tabs vs. spaces mix does lead to unexpected visual formatting (only OK in a properly configured text editor):
image

The only reason that occurred to leave as-is was the snippet being used for a straight comparison (`diff`) with the _xstar_ repository. Removing that as per the request.

**Comment by bodewig** [comment]
Well, first of all we are not all the same, my opinion may differ from the one of others who also contribute to COMPRESS. So take what I say with a big grain of salt, please. To me readable diffs are far more important than sticking to arbitrary formatting rules, so my first rule would be to never change the formatting of existing code - if it really seems necessary, do it in a different step so that the noise of whitespace changes doesn't distract from what you really wanted to change.

**Comment by bodewig** [comment]
I've merged your first two commits, thanks again.

**Pull request closed without merging**
