### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yishaigalatzer**
Change Craete -> Create

### CODE REVIEW

**Comment by bodewig** [comment]
Thank you.

I hope you are aware this is a pull request against a branch that's just been stashed away, is no longer under development and will never get merged to master.

**Comment by yishaigalatzer** [comment]
Thanks for responding quickly. Sure, still typos should be cleaned up.

**Comment by bodewig** [comment]
Thanks, I've merged your PR more than 24 hours ago https://git-wip-us.apache.org/repos/asf?p=commons-compress.git;a=shortlog;h=refs/heads/high-level-api-example but the change hasn't been replicated to github, yet.

**Comment by bodewig** [comment]
could you please close this PR? It seems only commits to master can trigger that.

**Pull request closed without merging**
