### PR TITLE
Remove out of date jar and scripts

### PR DESCRIPTION
**Pull request by beatbrot**
Using the maven wrapper is currently broken since the `org.apache.maven.plugins:maven-enforcer-plugin`  plugin requires at least maven 3.6.3. The committed maven wrapper uses version 3.5.0.

This PR updates the wrapper straight to 3.9.6 which fixes the issue.

### CODE REVIEW

**Comment by garydgregory** [comment]
We have jar files in the repository? Gross. I'd rather get rid of this since it will automatically go out of date with the next release, and the next one. I never use it. The GitHub CI doesn't either.

**Comment by beatbrot** [comment]
I mean...personally, I like the wrapper scripts. But if you want, I can change this PR to simply remove the wrapper :) Should I do that?

**Comment by garydgregory** [comment]
Hi @beatbrot 
Let's see if anyone else chimes in who is in love with these scripts...

**Comment by garydgregory** [comment]
> I mean...personally, I like the wrapper scripts. But if you want, I can change this PR to simply remove the wrapper :) Should I do that?

Sure, go for it. TY.

**Comment by beatbrot** [comment]
@garydgregory Done :)

**Pull request merged**
