### PR TITLE
feat: support for non-ASCII characters in GzipCompressorOutputStream filename

### PR DESCRIPTION
**Pull request by vincexjl**
support for non-ASCII characters in GzipCompressorOutputStream filename, can use parameters.setFilenameCharset(Charset.forName("GBK")) support windows with Chinese or parameters.setFilenameCharset(Charset.forName("UTF-8")) support linux with Chinese

See also [COMPRESS-638](https://issues.apache.org/jira/browse/COMPRESS-638)

### CODE REVIEW

**Comment by garydgregory** [comment]
Hello @vincexjl 

Thank you for your PR.

You'll have to provide unit tests to show that these changes work. The tests should fail when the change to 'main' are not applied.

All new public and protected code should have Javafoc with 'since tags.

Make sure you run "mvn" by itself before you push.

Do you have a link to the Gzip specification that define that non-ASCII bytes are allowed?

Ty.

**Comment by vincexjl** [comment]
hello @garydgregory 
thank you for your reply.
I have submitted new unit test
About Gzip specification that define that non-ASCII bytes are allowed:
when your system is Windows in Chinese, if your filename is Chinese, need encode filename to GBK, otherwise your filename will different with use GzipCompressorOutputStream(final OutputStream out) . it mean when we don`t use GzipParameters, the filename encode is decided by Operating system. and the same situation in linux need encode with  UTF-8

**Comment by ppkarwasz** [comment]
> Do you have a link to the Gzip specification that define that non-ASCII bytes are allowed?

According to [RFC 1952](https://datatracker.ietf.org/doc/html/rfc1952#page-7):

> If FNAME is set, an original file name is present, terminated by a zero byte.  The name must consist of ISO 8859-1 (LATIN-1) characters; on operating systems using EBCDIC or any other character set for file names, the name must be translated to the ISO LATIN-1 character set.

In practice utilities like GNU Gzip (see [`zip.c`](https://git.savannah.gnu.org/cgit/gzip.git/tree/zip.c)) do not care about that and put whatever sequence of bytes the filesystem uses. Anyway it doesn't matter, because by default the original file name is not restored (unless we have a filesystem that truncates file names).

Currently Commons Compress respects RFC 1952 and coerces file names to ISO 8859-1, but I guess we could introduce an option that uses `UTF-8` instead.

**Comment by garydgregory** [comment]
I know this kind of feature request has come up before but maybe not for this exact file format... (can't find a link atm)

This would likely cause interoperability issues but if a user wants to use the feature, especially to create non-standard file, then it would be up to them to document that.

**Comment by vincexjl** [comment]
@ppkarwasz @garydgregory 
hello thank you for your reply, 
as I was saying, when we use GzipCompressorOutputStream(final OutputStream out) . it mean when we don`t use GzipParameters, the filename encode is decided by Operating system. but when we use GzipParameters，the filename will encode by iso-8859-1 or new url encode. I think this is unreasonable. this will cause us to unzip the gzfile, filename is different with dont use GzipParameters. To maintain consistency, i think need add gzipParameter.setFilenameCharset to resolve it. I also kept it when we dont set this, still the same before when gzipParameters.getFilenameCharset is null

**Comment by garydgregory** [comment]
Hi @vincexjl 
I'll study the PR some more over the next couple of days. TY.

**Comment by ppkarwasz** [comment]
@vincexjl,

> To maintain consistency, i think need add gzipParameter.setFilenameCharset to resolve it.

IMHO the file names should always be encoded in `UTF-8`. This would ensure:

- Consistency between systems: a Gzip file created by Commons Compress on one system, could be read by Commons Compress on another system and the filename would not be mangled (as it happens today).
- A Gzip file created by Commons Compress, would be correctly handled by `gunzip` on a GNU/Linux system, since file names are encoded in `UTF-8` most of the time and `gunzip` copies the bytes as-is from the Gzip header. Note that the encoding of file names does not necessarily depend on the locale: GLib for example uses `UTF-8` regardless of the locale (see [their documentation](https://docs.gtk.org/glib/character-set.html#file-name-encodings)).
- It would be interesting to see how Windows applications handle Gzip files, e.g. 7-zip.

To achieve that, we could switch the default file name encoding to `UTF-8` and provide an option (e.g. `rfcCompliance`) to restore the file name mangling behavior. What do you think?

**Comment by garydgregory** [comment]
Hi @vincexjl , @ppkarwasz 

Let's see if we need more than what I put in git master. We have a new test that works for both the GBK and UTF-8 Charsets.

**Comment by ppkarwasz** [comment]
I have done a couple of tests on my Windows installation to see how Windows applications handle the filename encoding in Gzip. My locale has a default `WINDOWS-1250` charset, so it is easy to spot differences from both `UTF-8` and `ISO-8859-1`.

The behavior is highly **inconsistent**:

- Windows Explorer does **not** set a filename, when it creates `*.gz` archive.
- When opening an archive, Windows Explorer seems to use `ISO-8859-1` to decode the filename. So it **does not** use the default encoding (which is `WINDOWS-1250`).
- 7-Zip on the other hand sets a filename in the `*.gz` archives it creates. For that it uses the default (`WINDOWS-1250`) locale.

@vincexjl: does the Chinese version of Windows work differently?

@garydgregory,

I don't think there is  a reasonable way to handle file name encoding in the Gzip format. I would rather concentrate on solving the original problem, which was mangled file names (percent encoded).
What do you think about:

- Modifying the current logic to:
  1. Encode the filename as `ISO-8859-1`.
  2. If that can not be done just **drop** the filename field (which is optional anyway).
- Adding a `Boolean` option that allows users to override the behavior (either force the encoding of the filename or force the removal of the filename)

**Comment by garydgregory** [comment]
Hi @ppkarwasz and @vincexjl 

> Encode the filename as ISO-8859-1.

The name was already to ISO-8859-1 with an ASCII percent-encoded backstop. The behavior is still the same.

Now there is a Charset override.

I think I'm hearing you say, is that instead of falling back to ASCII percent-encoded, just don't write the name at all. Is that so?

I don't think that's the whole picture though but I could be wrong ;-)

I think the desire is to support simplified Chinese characters, and that can't be done with ISO-8859-1 (please correct me if I'm wrong).

I made a note in the Javadoc for `setFileNameCharset` that using a non-ISO-8859-1 Charest may cause interoperability issues.

WDYT?

**Comment by vincexjl** [comment]
@garydgregory @garydgregory 
thank your for  your reply
Let me explain in detail my discovery process. 
I use commons-compress version 1.21 in linux with Chninese language environment. The file name I am planning to compress is in Chinese, when I use 'GzipCompressorOutputStream(final OutputStream out)' to achieve compression into gz. When I extracted , the file name appears as normal in Chinese, whether using code or tool 7-zip.

but when I use 'GzipCompressorOutputStream(final OutputStream out, final GzipParameters parameters)' to setFilename in Chinese, the filename will become like ????.xml,  So I went to look through the version 1.21 source code.

if (filename != null) {
            this.out.write(filename.getBytes(StandardCharsets.ISO_8859_1));
            this.out.write(0);
        }

I guess that this does not support Chinese. So I modified it to  

‘this.out.write(filename.getBytes(StandardCharsets.UTF8));' to test it.  result performs correctly on Linux in Chinese language.

When I put my code on Windows in Chinese language. The file name is garbled, then I modified it to

‘this.out.write(filename.getBytes(Charset.forName("GBK"));' to test it.  result performs correctly on Windows in Chinese language.

I think maybe this is an unreasonable design, so I have decided to take a look at the latest version of the code.

I find version 1.27.2-SNAPSHOT in this scenario the filename will use 

'return new URI(null, null, string, null).toASCIIString().getBytes(StandardCharsets.US_ASCII);' to return filename。

This is not consistent with the performance in the scenario of using 'GzipCompressiorOutputStream (final OutputStream out)'.

If we set a Chinese file name, the extracted name will appear incorrect.

**Comment by garydgregory** [comment]
Hello @vincexjl,

Please try `1.28.0-SNAPSHOT` and use `GzipParameters.setFileNameCharset(Charset)`.

**Comment by garydgregory** [comment]
@ppkarwasz 

If you are saying that we should remove the ASCII-%-encoded backstop, I am OK with that.

**Comment by vincexjl** [comment]
@garydgregory 
Thanks very much
I have try 1.28.0-SNAPSHOT and use GzipParameters.setFileNameCharset(Charset). 
The performance is in line with expectations and I think it's possible to add this design

**Comment by ppkarwasz** [comment]
@garydgregory,

> I think what I'm hearing you say is, that instead of falling back to ASCII percent-encoded, just don't write the name at all. Is that so?

> If you are saying that we should remove the ASCII-%-encoded backstop, I am OK with that. I've not tried it so I do not know if that breaks some tests.

Certainly we should drop the `%`-encoding, since it serves no purpose other than RFC compliance. A mangled name is worse than no name at all and no Gzip decompressor handles that AFAIK.

We should probably also provide an option to decide whether to add the name or not. Note that:

- The original `gzip` utility **saves** the name upon compression, but does **not** restore it upon decompression.
- Windows Explorer does **not** save the name upon compression, but **restores** it upon decompression (as far as I could tell).

I believe that **not** storing the file name is the safest behavior, because in that case all applications fall back to inferring the uncompressed filename from the compressed filename.

**Remark**: I don't know what was the motivation behind this "filename" feature in Gzip, but I suspect that it was useful when the `.gz` file had a truncated name (e.g. on DOS filesystems, where the original name is truncated). These days it seems to be more of a nuisance than a feature. If you compress a logfile `log.1` to `log.1.gz` and then rename it to `log.2.gz`, the uncompressed file name is not renamed.

**Comment by vincexjl** [comment]
@ppkarwasz 
hello, I think I might share with you a scenario we encountered.
In your example, If you compress a logfile log.1 to log.1.gz and then rename it to log.2.gz, the uncompressed file name is not renamed.

In some cases, we use compress a logfile log.1 to log.1.gz and the rename it to log.1.gz.20241107, Like adding a time information after .gz

In order to quickly query some logs.

some system use tools like 7zip or winrar, they dont rename  log.1.gz.20241107 to log.1.gz, Open this compressed file directly in this scenario, the filename become  log.1.gz    

This is not what we want

but if we use GzipParameters .setFileName("log.1")

use like winrar  or 7-zip  open "log.1.gz.20241107" in this scenario, the fileName  still is "log.1"

This result is what we hope to achieve

**Comment by ppkarwasz** [comment]
> > We should probably also provide an option to decide whether to add the name or not.
> 
> Do you mean to not add the name if it cannot be encoded with the given Charset, or, do you mean adding an option to skip using the file name altogether and turn off the `FLG.FNAME` bit?

To keep it simple, maybe it is best to:

- [x] Introduce an option to set the character set (which you already did).
- [ ] Introduce an option that turns off and on `FLG.FNAME` and the filename field. I am not sure what the default value should be. Personally I would prefer to have this feature **off** by default (to prevent issue reports like apache/logging-log4j2#1870). We could also set it to the result of `CharSet.canEncode()`.
- [ ] If the filename field is enabled, use [`String.getBytes(CharSet)`](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#getBytes-java.nio.charset.Charset-) to fill it, without worrying about unmappable characters. The default behavior for those is:
    >This method always replaces malformed-input and unmappable-character sequences with this charset's default replacement byte array.

**Comment by ppkarwasz** [comment]
> > We should probably also provide an option to decide whether to add the name or not.
> 
> Do you mean to not add the name if it cannot be encoded with the given Charset, or, do you mean adding an option to skip using the file name altogether and turn off the `FLG.FNAME` bit?

I meant the second one, but it is a dumb proposal: you can already do that by setting `fileName` to `null`. :laughing: 
I would just replace:

https://github.com/apache/commons-compress/blob/ec7bc35bcacb8bf0aeb0f8611c7bea0b2f93b943/src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorOutputStream.java#L138-L145

with:

```java
return string.getBytes(charset);
```

The [`String.getBytes(CharSet)`](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#getBytes-java.nio.charset.Charset-) method does not throw:

> This method always replaces malformed-input and unmappable-character sequences with this charset's default replacement byte array.

**Comment by garydgregory** [comment]
Hi @ppkarwasz 

> return string.getBytes(charset);

I like the simplification :-) but, what about [COMPRESS-638](https://issues.apache.org/jira/browse/COMPRESS-638)?

**Comment by ppkarwasz** [comment]
> I like the simplification 😄 but, what about [COMPRESS-638](https://issues.apache.org/jira/browse/COMPRESS-638)?
> 
> Do we just say, use `GzipParameters.setFileNameCharset(Charset)` and adjust the tests to pass?

We could validate `GzipParameters` in the constructor of `GzipCompressorOutputStream` and throw if the filename can not be encoded.

**Comment by garydgregory** [comment]
> > I like the simplification 😄 but, what about [COMPRESS-638](https://issues.apache.org/jira/browse/COMPRESS-638)?
> > Do we just say, use `GzipParameters.setFileNameCharset(Charset)` and adjust the tests to pass?
> 
> We could validate `GzipParameters` in the constructor of `GzipCompressorOutputStream` and throw if the filename can not be encoded.

That would blow up existing call sites though.

I think we want to keep RFC behavior by default. We now provide a non-RFC override for the next release.

How about (maybe) :

The next release provides this new non-RFC feature. Apps can then adapt to it. The default behavior is the same.

For the release after that we can discuss changing the default behavior to no-longer % encode as a backstop, and adjust the tests.

Or is that slicing it too thin?

I'm concerned that adding another option now is too confusing. Not sure though. I'm not sure there is value in having an option to not use FNAME.

**Comment by ppkarwasz** [comment]
> How about (maybe) :
> 
> The next release provides this new non-RFC feature. Apps can then adapt to it. The default behavior is the same.
> 
> For the release after that we can discuss changing the default behavior to no-longer % encode as a backstop, and adjust the tests.
> 
> Or is that slicing it too thin?

I would rather revert the COMPRESS-638 and advertise this change as solution to that problem.

> I'm concerned that adding another option now is too confusing. Not sure though. I'm not sure there is value in having an option to not use FNAME.

As I [remarked in this comment](https://github.com/apache/commons-compress/pull/602#issuecomment-2462195805), there is already such an option: you just pass `null` as `fileName` or don't use `GzipParameters` at all. :wink:

**Comment by michael-o** [comment]
One must so the behavior of libarchive.

**Comment by garydgregory** [comment]
@ppkarwasz 

> I would rather revert the COMPRESS-638 fix and advertise this change as solution to that problem.

I'm think I'm OK with that. I'll experiment later.

@michael-o 

> One must so the behavior of libarchive.

I think it would help (me) if you quote what you're commenting on. Otherwise, I have no idea why item you are referring to.

**Comment by michael-o** [comment]
> @ppkarwasz
> 
> > I would rather revert the COMPRESS-638 fix and advertise this change as solution to that problem.
> 
> I think I'm OK with that. I'll experiment later.
> 
> @michael-o
> 
> > One must so the behavior of libarchive.
> 
> I think it would help (me) if you quote what you're commenting on. Otherwise, I have no idea why item you are referring to.

This refers to the fact how GNU tar this handles. As a contrast I would check bsdtar as well. For reference.

**Comment by ppkarwasz** [comment]
> > > One must so the behavior of libarchive.
> > 
> > I think it would help (me) if you quote what you're commenting on. Otherwise, I have no idea why item you are referring to.
> 
> This refers to the fact how GNU tar this handles. As a contrast I would check bsdtar as well. For reference.

I have checked both `gzip` and `zlib`. Since these are written in C, they operate on `\0`-terminated sequences of bytes. There is no character set conversion of any kind. On my Linux box, `gzip` uses the same encoding as the encoding of the filesystem (i.e. `UTF-8` in 99% of the cases).

**Comment by michael-o** [comment]
Just checked. Libiconv can be used.

**Comment by garydgregory** [comment]
Hi All,

Please pull from git master or the Maven snapshot repository where you'll find the US-ASCII hack removed.

**Pull request closed without merging**
