### PR TITLE
[COMPRESS-655] Fix TAR directory entries being misinterpreted as files

### PR DESCRIPTION
**Pull request by sschuberth**
As requested by @garydgregory.

### CODE REVIEW

**Comment by sschuberth** [comment]
Looks like in

    public boolean isFile() {
        if (file != null) {
            return Files.isRegularFile(file, linkOptions);
        }
        if (linkFlag == LF_OLDNORM || linkFlag == LF_NORMAL) {
            return true;
        }
        return !getName().endsWith("/");
    }

`file` is `null`, but `!getName().endsWith("/")` returns `true`. I'll investigate a bit further.

**Comment by sschuberth** [comment]
Ok, I believe to have a fix.

**Comment by garydgregory** [comment]
I have a fix as well ;-)

**Comment by sschuberth** [comment]
> I have a fix as well ;-)

Is it different from mine?

> Ah! You'll want to run `mvn` (by itself) before pushing to catch all build errors.

Should be all good now.

PS: I hope the test resource I've added is not too large... the uncompressed TAR is 1.9M 🙄

**Comment by garydgregory** [comment]
TY @sschuberth ! Merged.

**Comment by garydgregory** [comment]
https://issues.apache.org/jira/browse/COMPRESS-657

**Pull request merged**
