### PR TITLE
BZip2: Use BitInputStream

### PR DESCRIPTION
**Pull request by thomasmey**
And some minor spelling errors I stumbled upon.

### CODE REVIEW

**Comment by ebourg** [comment]
Is the performance equivalent with a BitInputStream?

**Comment by thomasmey** [comment]
Don't know. How to test? I think it very much depends on target architecture and JVM implementation. I could try to establish a baseline with a test case to check for regression. what do you think?

**Comment by bodewig** [comment]
Some rough comparisons for larger files would be a good indicator.

The existing code is pretty ugly because this seemed to be necessary for acceptable performance back then. "Back then" is JDK 1.3 or 1.4, though. Another aspect was that the code stayed close to libbzip2's C implementation which in theory would have allowed us to port changes - which I don't think has ever happened.

Do you think you could create separate PRs for your javadoc typo fixes and making methods static in GZIP? They are separate commits, which is most important to me, but separate PRs looks even cleaner :-)

**Comment by bodewig** [comment]
Sorry, I didn't realize you had updated the PR, will have a look later.

**Comment by bodewig** [comment]
I'm planning to set up a JMH based benchmark soonish and would like to get some statistical information before merging this.

**Comment by bodewig** [comment]
For starters, https://github.com/bodewig/commons-compress-benchmarks - right now I'm not sure where it'll end up.

**Comment by bodewig** [comment]
@thomasmey I've made some minor changes and pushed it to the branch PR13

My benchmarks at https://github.com/bodewig/commons-compress-benchmarks/wiki/PR13 sees the changed code within the error margins of the results for the master branch. @ebourg do you think this is sufficient or do you want to run tests of your own?

**Comment by bodewig** [comment]
I just realized I had benchmarked compression rather than decompression, I've now updated https://github.com/bodewig/commons-compress-benchmarks/wiki/PR13

Fortunately the result is the same, the results are basically the same (the mean of one measurement is within the error margin of the other). If anything then decompressing bigger files has become a bit faster.

**Pull request closed without merging**
