### PR TITLE
Whitespace improvement, site nits and assorted typos

### PR DESCRIPTION
**Pull request by HelderMagalhaes**
Closed PR 197 and PR 198, as those changes were also included here by mistake.

### CODE REVIEW

**Comment by PeterAlfredLee** [comment]
Hi @HelderMagalhaes 

Thank you for your contribution.

I'm a little confused about your PR #197, #198 and #199. They look pretty similar. What's the difference? It's appreciated if you can close the PRs you don't want to push.

BTW : there're so many commits in your PR. Could you squash them?

**Comment by HelderMagalhaes** [comment]
> I'm a little confused about your PR #197, #198 and #199. They look pretty similar. What's the difference? It's appreciated if you can close the PRs you don't want to push.

I did want to push but in different pull requests:
* PR 197 was regarding the "whitespace improvement" which had been submitted to PR 192 but didn't get through due to being mixed with other changed.
* PR 198 was regarding the "site nits", which are also included here
* The remaining part (the initial goal for this PR) are few typos noticed.

The idea was to keep this one, as it gathers all changes away, in the hope that mixing slightly different things, particularly whitespace ("If you feel the source code should be reformatted create a separate PR for this change first.", as also hinted by @bodewig in already referred PR 192) isn't a problem. Otherwise I'll also close this PR and try resubmit all three. What do you think?


> BTW : there're so many commits in your PR. Could you squash them?

If there's a need to resubmit the PR I'll take that into consideration. Thanks for the feedback.

**Comment by PeterAlfredLee** [comment]
> The idea was to only keep this one, as it gathers all changes away, in the hope that mixing slightly different things,

I see. So this PR contains some typo fix and reformatings.

> Otherwise I'll also close this PR and try resubmit all three. What do you think?

This PR looks good to me. WDYT @bodewig ?

> If there's a need to resubmit the PR I'll take that into consideration. 

You don't have to resubmit a PR to squash commits. A `git rebase` and a `git push --force` in your branch `HelderMagalhaes:assorted-typos` is enough.

**Comment by garydgregory** [comment]
Please rebase on master. Recent changes should allow all builds to be green including Java 16 and 17-EA.

**Comment by HelderMagalhaes** [comment]
Closing down this PR as it seemed to get rot, possibly due to something wrong during rebase. Will open a new one briefly. Thanks to @PeterAlfredLee for the feedback.

**Pull request closed without merging**
