### PR TITLE
Performance test for BZip2CompressorOutputStream

### PR DESCRIPTION
**Pull request by XenoAmess**
@bodewig 
So I tried to make a refine for `BZip2CompressorOutputStream` yesterday.
for conclusion,
1. adding the break seems at least not letting it slower.
so we donot need to revert that change yesterday.
2. the codes right now is really fast.
I mean, all of my refine tries seems no significant improvement for performance.
3. the refine method I tried:
3.0 class `BZip2CompressorOutputStream` is the class in branch master now(with break). class `BZip2CompressorOutputStreamNonBreak` is the version without break.
3.1. class `BZip2CompressorOutputStreamXenoAmessInShort` : aims to use `short` instead of `boolean` in `Data.inUse` array, and use bit operations for copy/change.
3.2. class `BZip2CompressorOutputStreamXenoAmessInBoolean` : aims to inline more, and added some small changes.
3.3 class `BZip2CompressorOutputStreamXenoAmessInBoolean2` : aims to inline as LEAST methods as we can, and wholly trust JIT will give it a good C2.
and the result of performance test shows that there are nearly no difference in speed actually, and `BZip2CompressorOutputStream` runs slightly (very slightly) faster than others.(which means all of my refinitions failed)
But, as all known, jmh is actually not a stable thing, so as the diffenerce are really small, I think it is the right time for me to surrender and stop trying to refine it using my tricky ways.
And the `BZip2CompressorOutputStream` in master now is good. No need to revert the `break`. at least on win10, jdk13.
Althought the refining-try failed, maybe the performance test codes and the "refined"(or, variant actually, as they does not refine anything) classes might be useful.
I just put them in the test folder, and maybe next time when some guy wanna refine this class, they can at least know in what ways I failed and stop waste time on it.

### CODE REVIEW

**Comment by XenoAmess** [comment]
Now I will add the `break` and make BZip2CompressorOutputStream equal to what in branch master.

**Comment by XenoAmess** [comment]
wait a minute. some thing might goes wrong. I will have to recheck it.

**Comment by XenoAmess** [comment]
result json
```
[
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testOld",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 1231787.9057171796,
            "scoreError" : 60747.12958923382,
            "scoreConfidence" : [
                1171040.7761279459,
                1292535.0353064134
            ],
            "scorePercentiles" : {
                "0.0" : 1117403.0066815144,
                "50.0" : 1206172.8915662651,
                "90.0" : 1357090.8833458365,
                "95.0" : 1397579.7860595766,
                "99.0" : 1407715.308988764,
                "99.9" : 1407715.308988764,
                "99.99" : 1407715.308988764,
                "99.999" : 1407715.308988764,
                "99.9999" : 1407715.308988764,
                "100.0" : 1407715.308988764
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    1177021.6204465334,
                    1127303.7109111361,
                    1258797.7415307402,
                    1315991.2073490813,
                    1205418.4115523465
                ],
                [
                    1117403.0066815144,
                    1120983.110738255,
                    1206172.8915662651,
                    1235757.2839506173,
                    1288148.2670089859
                ],
                [
                    1345864.6505376345,
                    1249905.6097256858,
                    1229342.455214724,
                    1174833.6471277843,
                    1373930.2325581396
                ],
                [
                    1407715.308988764,
                    1319910.290237467,
                    1196952.9916267942,
                    1191689.535077289,
                    1191617.3590963138
                ],
                [
                    1161137.9350348029,
                    1247206.3354037267,
                    1329505.9760956175,
                    1134020.724801812,
                    1188067.3396674583
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testOldWithNonBreak",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 1232199.7367553925,
            "scoreError" : 49896.117650952154,
            "scoreConfidence" : [
                1182303.6191044403,
                1282095.8544063447
            ],
            "scorePercentiles" : {
                "0.0" : 1138645.4545454546,
                "50.0" : 1220320.2451219512,
                "90.0" : 1330014.3934583652,
                "95.0" : 1416521.2841356166,
                "99.0" : 1447036.6379310344,
                "99.9" : 1447036.6379310344,
                "99.99" : 1447036.6379310344,
                "99.999" : 1447036.6379310344,
                "99.9999" : 1447036.6379310344,
                "100.0" : 1447036.6379310344
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    1219577.6155717762,
                    1217867.5182481753,
                    1239696.6530359355,
                    1345318.7919463087,
                    1188941.567695962
                ],
                [
                    1220320.2451219512,
                    1178962.190812721,
                    1150802.0665901264,
                    1189386.9513641756,
                    1259764.5283018867
                ],
                [
                    1319811.4611330698,
                    1242681.3895781639,
                    1281534.9551856595,
                    1190924.3745541023,
                    1253228.9637952559
                ],
                [
                    1235037.6543209876,
                    1207377.376654633,
                    1169074.7651869159,
                    1166782.2843822844,
                    1138645.4545454546
                ],
                [
                    1201098.4412470025,
                    1236322.207361963,
                    1447036.6379310344,
                    1277316.0114358324,
                    1227483.3128834355
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testOldWithNonBreak_large",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 2.12021302408E9,
            "scoreError" : 2.360493324134416E8,
            "scoreConfidence" : [
                1.8841636916665583E9,
                2.3562623564934416E9
            ],
            "scorePercentiles" : {
                "0.0" : 1.714751701E9,
                "50.0" : 2.0113718E9,
                "90.0" : 2.4311222794E9,
                "95.0" : 2.969229799299999E9,
                "99.0" : 3.189218899E9,
                "99.9" : 3.189218899E9,
                "99.99" : 3.189218899E9,
                "99.999" : 3.189218899E9,
                "99.9999" : 3.189218899E9,
                "100.0" : 3.189218899E9
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    1.9268256E9,
                    2.043991299E9,
                    1.953332401E9,
                    1.931591201E9,
                    2.0113718E9
                ],
                [
                    2.087423201E9,
                    1.900431E9,
                    1.762311301E9,
                    1.9722613E9,
                    1.907756499E9
                ],
                [
                    1.8461512E9,
                    1.892023E9,
                    1.714751701E9,
                    1.834355999E9,
                    1.9544061E9
                ],
                [
                    2.292780701E9,
                    2.3383052E9,
                    2.293059001E9,
                    2.3146227E9,
                    2.4559219E9
                ],
                [
                    2.2952725E9,
                    2.400574801E9,
                    2.271997099E9,
                    2.414589199E9,
                    3.189218899E9
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testOld_large",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 2.04161031588E9,
            "scoreError" : 1.5706752909928608E8,
            "scoreConfidence" : [
                1.884542786780714E9,
                2.198677844979286E9
            ],
            "scorePercentiles" : {
                "0.0" : 1.7256607E9,
                "50.0" : 2.0307501E9,
                "90.0" : 2.38786736E9,
                "95.0" : 2.46114804E9,
                "99.0" : 2.474493E9,
                "99.9" : 2.474493E9,
                "99.99" : 2.474493E9,
                "99.999" : 2.474493E9,
                "99.9999" : 2.474493E9,
                "100.0" : 2.474493E9
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    2.1016981E9,
                    2.0642726E9,
                    2.1872375E9,
                    2.121889301E9,
                    2.0307501E9
                ],
                [
                    1.955578901E9,
                    1.8177623E9,
                    1.8317769E9,
                    1.874995699E9,
                    1.8382277E9
                ],
                [
                    2.474493E9,
                    2.3597724E9,
                    2.2458188E9,
                    2.4300098E9,
                    2.193804199E9
                ],
                [
                    1.7908164E9,
                    1.920142699E9,
                    1.750905001E9,
                    1.7256607E9,
                    1.918628999E9
                ],
                [
                    2.0677578E9,
                    2.003415199E9,
                    2.2743971E9,
                    1.9448107E9,
                    2.115635999E9
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testXenoAmessBoolean",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 1246764.5772065748,
            "scoreError" : 74547.98612210396,
            "scoreConfidence" : [
                1172216.591084471,
                1321312.5633286787
            ],
            "scorePercentiles" : {
                "0.0" : 1116264.6982182628,
                "50.0" : 1223564.47008547,
                "90.0" : 1395859.386356086,
                "95.0" : 1533512.0073060496,
                "99.0" : 1576530.501572327,
                "99.9" : 1576530.501572327,
                "99.99" : 1576530.501572327,
                "99.999" : 1576530.501572327,
                "99.9999" : 1576530.501572327,
                "100.0" : 1576530.501572327
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    1300187.142857143,
                    1198462.994011976,
                    1185104.8578199053,
                    1171811.3450292398,
                    1251268.25
                ],
                [
                    1180054.5146541619,
                    1433135.520684736,
                    1258284.1695979899,
                    1189417.4791914388,
                    1263270.9962168979
                ],
                [
                    1188949.6448931117,
                    1137079.8185941044,
                    1245094.169975186,
                    1223564.47008547,
                    1116264.6982182628
                ],
                [
                    1194806.6825775655,
                    1223727.0171149145,
                    1168115.6371061844,
                    1262649.684741488,
                    1371008.6301369863
                ],
                [
                    1283710.8834827144,
                    1213653.5108958837,
                    1195208.6021505375,
                    1337753.2085561496,
                    1576530.501572327
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testXenoAmessBoolean2",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 1306858.2145612794,
            "scoreError" : 72285.49884668845,
            "scoreConfidence" : [
                1234572.7157145909,
                1379143.713407968
            ],
            "scorePercentiles" : {
                "0.0" : 1187167.1423487545,
                "50.0" : 1294347.4160206718,
                "90.0" : 1464736.5628157454,
                "95.0" : 1551573.7845849802,
                "99.0" : 1555641.7701863353,
                "99.9" : 1555641.7701863353,
                "99.99" : 1555641.7701863353,
                "99.999" : 1555641.7701863353,
                "99.9999" : 1555641.7701863353,
                "100.0" : 1555641.7701863353
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    1285297.944801027,
                    1413173.059238364,
                    1277114.156887755,
                    1296659.3023255814,
                    1206067.5903614457
                ],
                [
                    1232945.5104551045,
                    1227347.7478684532,
                    1349307.4123989218,
                    1311445.2162516383,
                    1294939.3054123712
                ],
                [
                    1246975.0,
                    1260959.9496221663,
                    1363623.568119891,
                    1300410.505836576,
                    1381948.6225895316
                ],
                [
                    1187751.9584816133,
                    1192419.5950118764,
                    1187167.1423487545,
                    1542081.8181818181,
                    1386742.6002766252
                ],
                [
                    1356159.3482384824,
                    1555641.7701863353,
                    1268342.9670468948,
                    1294347.4160206718,
                    1252585.8560700875
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testXenoAmessBoolean2_large",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 2.14501156404E9,
            "scoreError" : 1.4318871314573377E8,
            "scoreConfidence" : [
                2.0018228508942661E9,
                2.288200277185734E9
            ],
            "scorePercentiles" : {
                "0.0" : 1.7524246E9,
                "50.0" : 2.1855709E9,
                "90.0" : 2.4107346798E9,
                "95.0" : 2.427149341E9,
                "99.0" : 2.433456301E9,
                "99.9" : 2.433456301E9,
                "99.99" : 2.433456301E9,
                "99.999" : 2.433456301E9,
                "99.9999" : 2.433456301E9,
                "100.0" : 2.433456301E9
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    2.409602399E9,
                    2.2068406E9,
                    2.412433101E9,
                    2.1855709E9,
                    2.2227325E9
                ],
                [
                    1.9115948E9,
                    1.7524246E9,
                    1.7780846E9,
                    1.9251865E9,
                    1.788871201E9
                ],
                [
                    2.088532799E9,
                    2.2184606E9,
                    2.0720513E9,
                    2.208279999E9,
                    2.1775286E9
                ],
                [
                    2.0896588E9,
                    2.0991648E9,
                    2.115954899E9,
                    2.147097601E9,
                    2.2140105E9
                ],
                [
                    2.247852901E9,
                    2.3233761E9,
                    2.2582152E9,
                    2.433456301E9,
                    2.3383075E9
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testXenoAmessBoolean_large",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 2.10666797612E9,
            "scoreError" : 1.858098340238573E8,
            "scoreConfidence" : [
                1.9208581420961425E9,
                2.292477810143857E9
            ],
            "scorePercentiles" : {
                "0.0" : 1.7088213E9,
                "50.0" : 2.1619656E9,
                "90.0" : 2.4410814006E9,
                "95.0" : 2.50018564E9,
                "99.0" : 2.5164241E9,
                "99.9" : 2.5164241E9,
                "99.99" : 2.5164241E9,
                "99.999" : 2.5164241E9,
                "99.9999" : 2.5164241E9,
                "100.0" : 2.5164241E9
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    2.2294312E9,
                    2.1356383E9,
                    2.064529599E9,
                    2.1939016E9,
                    2.181651701E9
                ],
                [
                    1.8551577E9,
                    1.7994689E9,
                    1.775201799E9,
                    1.7088213E9,
                    1.8739581E9
                ],
                [
                    2.2601573E9,
                    2.4622959E9,
                    2.3076374E9,
                    2.4137872E9,
                    2.426938401E9
                ],
                [
                    2.5164241E9,
                    2.2391286E9,
                    2.255470101E9,
                    2.397133601E9,
                    2.1619656E9
                ],
                [
                    1.865237301E9,
                    1.9367017E9,
                    1.7546373E9,
                    1.8668675E9,
                    1.9845572E9
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testXenoAmessShort",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 1297103.3636990814,
            "scoreError" : 136111.28365654423,
            "scoreConfidence" : [
                1160992.080042537,
                1433214.6473556256
            ],
            "scorePercentiles" : {
                "0.0" : 1109964.302660754,
                "50.0" : 1249577.1535580524,
                "90.0" : 1563933.7866650722,
                "95.0" : 1849929.0632876495,
                "99.0" : 1896727.97731569,
                "99.9" : 1896727.97731569,
                "99.99" : 1896727.97731569,
                "99.999" : 1896727.97731569,
                "99.9999" : 1896727.97731569,
                "100.0" : 1896727.97731569
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    1170425.4672897197,
                    1179550.2358490566,
                    1140608.2086659065,
                    1109964.302660754,
                    1350190.4197031038
                ],
                [
                    1260401.5094339622,
                    1196957.6372315036,
                    1128279.6400449944,
                    1159284.1251448435,
                    1191038.049940547
                ],
                [
                    1248003.4925187032,
                    1446068.5796269728,
                    1291581.4206451613,
                    1289232.3037323037,
                    1350836.2533692722
                ],
                [
                    1896727.97731569,
                    1740731.5972222222,
                    1387759.0594744121,
                    1315878.374836173,
                    1188316.2502965599
                ],
                [
                    1220996.3459196102,
                    1264384.508816121,
                    1249577.1535580524,
                    1238748.0198019801,
                    1412043.1593794075
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    },
    {
        "jmhVersion" : "1.21",
        "benchmark" : "org.apache.commons.compress.performance.BZip2CompressorOutputStreamXenoAmessTest.testXenoAmessShort_large",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "C:\\jdk-13.0.2+8\\bin\\java.exe",
        "jvmArgs" : [
        ],
        "jdkVersion" : "13.0.2",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "13.0.2+8",
        "warmupIterations" : 5,
        "warmupTime" : "1000 ms",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "1000 ms",
        "measurementBatchSize" : 1,
        "primaryMetric" : {
            "score" : 2.09339351196E9,
            "scoreError" : 1.2512245349525204E8,
            "scoreConfidence" : [
                1.968271058464748E9,
                2.218515965455252E9
            ],
            "scorePercentiles" : {
                "0.0" : 1.8459343E9,
                "50.0" : 2.0743201E9,
                "90.0" : 2.3058365E9,
                "95.0" : 2.5182839307E9,
                "99.0" : 2.603713101E9,
                "99.9" : 2.603713101E9,
                "99.99" : 2.603713101E9,
                "99.999" : 2.603713101E9,
                "99.9999" : 2.603713101E9,
                "100.0" : 2.603713101E9
            },
            "scoreUnit" : "ns/op",
            "rawData" : [
                [
                    2.1299155E9,
                    1.927480199E9,
                    2.1137672E9,
                    1.9866811E9,
                    2.0261248E9
                ],
                [
                    2.3189492E9,
                    2.0734621E9,
                    2.603713101E9,
                    2.0743201E9,
                    2.074657599E9
                ],
                [
                    1.866583099E9,
                    2.0578543E9,
                    2.216846501E9,
                    2.2970947E9,
                    1.8459343E9
                ],
                [
                    1.9114012E9,
                    2.2009864E9,
                    1.891853699E9,
                    1.9916818E9,
                    2.1050026E9
                ],
                [
                    2.0214512E9,
                    2.1630685E9,
                    2.1695999E9,
                    2.0180235E9,
                    2.248385201E9
                ]
            ]
        },
        "secondaryMetrics" : {
        }
    }
]
```

**Comment by XenoAmess** [comment]
for new commers, the last conversation happened in https://github.com/apache/commons-compress/pull/106

**Comment by PeterAlfredLee** [comment]
Hey @XenoAmess 
What is this PR helping? From my view, you are providing some test results for you PR #106. This PR is not intended to be merged but give some explanizations for #106, is it?

**Comment by XenoAmess** [comment]
> This PR is not intended to be merged but give some explanizations for #106,
indeed.

**Comment by PeterAlfredLee** [comment]
No doubt the break won't make things worse.

Sometimes it's more difficult to optimize projects writen by JAVA than ones writen by C. We can use SIMD/SSE and some other optimizations in C but not in JAVA, which is a common and pretty efficent way to optimize performance in projects with lot of computations, like compression. Seems the JIT can provide some optimizations in Runtime but it's controled by JVM itself.

**Comment by XenoAmess** [comment]
> Seems the JIT can provide some optimizations in Runtime but it's controled by JVM itself.
Yep, JIT seesm an amazing black box.

**Pull request closed without merging**
