### PR TITLE
OMPRESS-565 : add BufferPool support in zstd

### PR DESCRIPTION
**Pull request by PeterAlfredLee**
Add `BufferPool` as a configuration of `ZstdCompressorInputStream`

### CODE REVIEW

**Comment by heuermh** [comment]
See also #163

**Comment by heuermh** [comment]
Thanks @PeterAlfredLee!

This LGTM for the use case where callers are using the `ZstdCompressorInputStream` constructor directly.

How might we support the [`CompressorStreamFactory.createCompressorInputStream(InputStream)`](
http://commons.apache.org/proper/commons-compress/javadocs/api-release/org/apache/commons/compress/compressors/CompressorStreamFactory.html#createCompressorInputStream-java.io.InputStream-) use case?

**Comment by PeterAlfredLee** [comment]
> See also #163

I can't see much differences between 1.4.8-1 and 1.4.8-3 of `zstd-jni`. Besides that, 1.4.8-4 is on the way(released 2 days ago).
I think we can leave the pom as it is.

**Comment by PeterAlfredLee** [comment]
> How might we support the CompressorStreamFactory.createCompressorInputStream(InputStream) use case?

-1. We do not support detailed configurations in `CompressorStreamFactory`. It's a simple input stream factory with compressor type detectors. I think we should keep it simple enough.

**Comment by heuermh** [comment]
> > How might we support the CompressorStreamFactory.createCompressorInputStream(InputStream) use case?
> 
> -1. We do not support detailed configurations in `CompressorStreamFactory`. It's a simple input stream factory with compressor type detectors. I think we should keep it simple enough.

Fair enough.  I can do the stream format check beforehand; I use `CompressorStreamFactory` as a fallback.

**Pull request merged**
