### PR TITLE
COMPRESS-641: add getLinkFlag for TarArchiveEntry

### PR DESCRIPTION
**Pull request by XenoAmess**
Hi.
I'm making a tar compressing tool.
And I need to know what the original flag of a tar entry I read, otherwise I would make it changed in the decompressed result...

### CODE REVIEW

**Review by garydgregory — CHANGES_REQUESTED** [review]
-1:  Javadoc is completely wrong; no unit test.

**Review by kinow — COMMENTED** [review]
@XenoAmess are you going to retrieve the `linkFlag` byte value, and then compare doing something like `if (linkFlag == SOME_CONSTANT) {} else if (linkFlag == ANOTHER_CONSTANT) { ... }` ?

If so, would it be possible to instead use the public methods like `if (obj.isBlockDevice())`, `else if (obj.isCharacterDevice())`, etc., instead?

Just checking if there's no alternative to making this property public.

Cheers,

-Bruno

**Comment by XenoAmess** [comment]
> @XenoAmess are you going to retrieve the `linkFlag` byte value, and then compare doing something like `if (linkFlag == SOME_CONSTANT) {} else if (linkFlag == ANOTHER_CONSTANT) { ... }` ?
> 
> If so, would it be possible to instead use the public methods like `if (obj.isBlockDevice())`, `else if (obj.isCharacterDevice())`, etc., instead?
> 
> Just checking if there's no alternative to making this property public.
> 
> Cheers,
> 
> -Bruno

no, I would put it directly into the output tar

the mechenism of my compression is only compress entries with some linkFlag types.

for others, just make them same and clone them directly into the output compressed tar.

**Comment by XenoAmess** [comment]
> -1: Javadoc is completely wrong; no unit test.

javadoc fixed.

Would add unit test, but I want to know about your opinons about exposing such a field first.

If made sure you don't mind we expose it, then I would add the unit tests.

**Comment by garydgregory** [comment]
Adding the getter seems reasonable to me as it is documented here if I am reading correctly: https://www.gnu.org/software/tar/manual/html_node/Standard.html

**Comment by kinow** [comment]
> Adding the getter seems reasonable to me as it is documented here if I am reading correctly: https://www.gnu.org/software/tar/manual/html_node/Standard.html

Yeah, I was trying to think in other ways to solve what @XenoAmess needed without adding that getter (as there are other properties that are private only, without getters), but I can't think of an alternative. So +1 to the getter too.

**Comment by XenoAmess** [comment]
@garydgregory 
unit tests added.

**Review by kinow — APPROVED** [review]
Just needs to squash commits. Otherwise, looks good to me! Thanks @XenoAmess !

**Comment by XenoAmess** [comment]
> Just needs to squash commits. Otherwise, looks good to me! Thanks @XenoAmess !

@kinow squashed

**Review by kinow — APPROVED** [review]

**Pull request merged**
