### PR TITLE
remove `== null` as it is covered by `instance of`

### PR DESCRIPTION
**Pull request by XenoAmess**
Or, is it for special optimization strategy?

### CODE REVIEW

**Comment by PeterAlfredLee** [comment]
Not sure if this is caused by Sonarqube or some other scans. From my view the null check is not needed here.

**Comment by bodewig** [comment]
@PeterAlfredLee are you talking about the decreased coverage? This happens because the builds on different JDKs end with slightly different results and so the coverage fluctuates a bit depending on which JDK's build finishes first.

**Comment by PeterAlfredLee** [comment]
> are you talking about the decreased coverage

Nope, I was just wondering if the null check here is caused by some type of static analysis like FindBugs or Sonarqube. This PR looks good to me - if it's not because of some static analysis tool.

> This happens because the builds on different JDKs end with slightly different results and so the coverage fluctuates a bit depending on which JDK's build finishes first.

So that's the reason why the coverage varies when no code is changed. Thank you for your explanation.

**Comment by bodewig** [comment]
thanks @XenoAmess

**Pull request merged**
